const Games={};
Games.wordle=function wordle(){
let A=["APPLE","BRAIN","CLOUD","CRANE","DREAM","EARTH","FLAME","GRAPE","HOUSE","LIGHT","MUSIC","NIGHT","OCEAN","PIANO","PLANT","QUEST","RADIO","RIVER","SHARE","SMILE","SPACE","STONE","STORM","TABLE","TRAIN","TRUST","WATER","WORLD","WRITE","ZEBRA","ABOUT","ABOVE","AFTER","AGAIN","ALONE","ANGEL","BEACH","BLACK","BLAME","BLEND","BRAVE","BREAD","BREAK","BRING","BROWN","CHAIR","CHECK","CHESS","CHILD","CLEAN","CLEAR","CLIMB","CLOCK","CLOSE","COACH","COAST","COLOR","COUNT","COURT","COVER","CRISP","CROWN","DAILY","DANCE","DRINK","DRIVE","EARLY","EMPTY","ENJOY","ENTER","EQUAL","FAITH","FIELD","FINAL","FIRST","FRESH","FRONT","FRUIT","GIANT","GLASS","GLOBE","GREAT","GREEN","GROUP","HAPPY","HEART","HEAVY","HORSE","HOTEL","IMAGE","INDEX","INNER","INPUT","ISSUE","JUICE","KNIFE","LARGE","LEARN","LEAST","LEMON","LEVEL","LOCAL","MAGIC","MAJOR","MARCH","MATCH","MAYBE","MODEL","MONEY","MONTH","MOUSE","MOVIE","NEVER","NORTH","OFFER","ORDER","OTHER","PAINT","PAPER","PARTY","PEACE","PHONE","PIECE","PILOT","PLACE","PLAIN","PLANE","POINT","POWER","PRESS","PRICE","PRIDE","PRIME","PRINT","PROUD","QUICK","QUIET","QUEEN","RAISE","REACH","READY","RIGHT","ROUND","ROYAL","SCALE","SCORE","SHAPE","SHORT","SIGHT","SIMPLE","SKILL","SMALL","SMART","SOLID","SOUND","SOUTH","SPEAK","SPEED","SPEND","SPORT","STAGE","START","STATE","STEAM","STEEL","STICK","STILL","STOCK","STORE","STORY","STUDY","SUGAR","TEACH","THANK","THEME","THERE","THICK","THING","THINK","THROW","TIGER","TODAY","TOPIC","TOTAL","TOUCH","TOWER","TRACK","TRADE","TREAT","TRUTH","UNCLE","UNDER","UNION","UNITY","UNTIL","UPPER","VALUE","VIDEO","VISIT","VOICE","WATCH","WHICH","WHITE","WHOLE","WOMAN","WORRY","YOUNG","ZEBRA"],
ans=A[Math.random()*A.length|0],g=Array.from({length:6},()=>Array(5).fill("")),states=Array.from({length:6},()=>Array(5).fill("")),r=0,c=0,done=false;
root.innerHTML='<div class="toolbar"><span class="pill">6 attempts</span><span class="pill">5 letters</span><button class="ghost" id="hintBtn">💡 Hint</button></div><div class="wordle-layout"><div class="wb" id="wb"></div><div class="keys" id="keys"></div></div><div class="msg" id="wm">Type a word or use the keyboard.</div>';
function draw(){
wb.innerHTML=g.map((x,i)=>'<div class="wr">'+x.map((v,j)=>'<div class="wc '+(v?"filled ":"")+(states[i][j]||"")+'">'+v+"</div>").join("")+"</div>").join("");
keys.innerHTML=["QWERTYUIOP","ASDFGHJKL","ZXCVBNM"].map((x,i)=>'<div class="kr">'+(i==2?'<button class="key wide" data-k="ENTER">ENTER</button>':"")+x.split("").map(k=>'<button class="key" data-k="'+k+'">'+k+"</button>").join("")+(i==2?'<button class="key wide" data-k="BACK">⌫</button>':"")+"</div>").join("");
keys.querySelectorAll("button").forEach(b=>b.onclick=()=>press(b.dataset.k));
updateKeyboard();
}
function updateKeyboard(){
const rank={absent:1,present:2,correct:3},best={};
states.forEach(row=>row.forEach((st,i)=>{if(st){let ch=g[states.indexOf(row)][i];if(!best[ch]||rank[st]>rank[best[ch]])best[ch]=st}}));
keys.querySelectorAll(".key").forEach(b=>{let k=b.dataset.k;if(best[k])b.classList.add(best[k])});
}
function press(k){
if(done)return;
if(k=="BACK"){if(c){c--;g[r][c]=""}}
else if(k=="ENTER")submit();
else if(/^[A-Z]$/.test(k)&&c<5)g[r][c++]=k;
draw();
}
function submit(){
if(c<5){wm.textContent="Enter 5 letters.";return}
let q=g[r].join("");
if(!A.includes(q)){wm.textContent="Not in the Wordle word list.";return}
let remaining={};ans.split("").forEach(ch=>remaining[ch]=(remaining[ch]||0)+1);
let result=Array(5).fill("absent");
q.split("").forEach((ch,i)=>{if(ch==ans[i]){result[i]="correct";remaining[ch]--}});
q.split("").forEach((ch,i)=>{if(result[i]=="absent"&&remaining[ch]>0){result[i]="present";remaining[ch]--}});
states[r]=result;
draw();
if(q==ans){done=true;wm.textContent="Solved in "+(r+1)+" tries! 🎉";record("wordle",r+1)}
else if(r==5){done=true;wm.textContent="The word was "+ans+"."}
else{r++;c=0;wm.textContent="Try again — green = correct, yellow = wrong position, white = not in word."}
draw();
}
const keyHandler=e=>{if(!modal.classList.contains("off")){if(e.key=="Enter")press("ENTER");else if(e.key=="Backspace")press("BACK");else if(/^[a-zA-Z]$/.test(e.key))press(e.key.toUpperCase())}};
document.addEventListener("keydown",keyHandler);
cleanupGame=()=>document.removeEventListener("keydown",keyHandler);
draw();
$("#hintBtn").onclick=()=>{let missing=ans.split("").map((ch,i)=>g.flat().includes(ch)?null:(i+1)+":"+ch).filter(Boolean);wm.textContent=missing.length?"💡 Hint: position "+missing[0].split(":")[0]+" is '"+missing[0].split(":")[1]+"'.":"💡 Hint: use the colors from your previous guesses.";
};
}
Games.chess=function chess(){let B=[["♜","♞","♝","♛","♚","♝","♞","♜"],["♟","♟","♟","♟","♟","♟","♟","♟"],...Array(4).fill(0).map(()=>Array(8).fill("")),["♙","♙","♙","♙","♙","♙","♙","♙"],["♖","♘","♗","♕","♔","♗","♘","♖"]],white=new Set(["♙","♖","♘","♗","♕","♔"]),turn="w",sel=null,legal=[];root.innerHTML='<div class="toolbar"><span class="pill" id="turn">White to move</span><button class="ghost" id="resetC">Reset</button></div><div class="cb" id="cb"></div><div class="msg" id="cm">Click a piece, then a highlighted square.</div>';let cb=$("#cb");function color(p){return white.has(p)?"w":"b"}function type(p){if("♙♟".includes(p))return"p";if("♖♜".includes(p))return"r";if("♘♞".includes(p))return"n";if("♗♝".includes(p))return"b";if("♕♛".includes(p))return"q";return"k"}function inBoard(r,c){return r>=0&&r<8&&c>=0&&c<8}function moves(r,c){let p=B[r][c],own=color(p),t=type(p),out=[],push=(rr,cc)=>{if(!inBoard(rr,cc))return false;if(!B[rr][cc]){out.push([rr,cc]);return true}if(color(B[rr][cc])!==own&&type(B[rr][cc])!=="k")out.push([rr,cc]);return false};if(t==="p"){let d=own==="w"?-1:1,s=own==="w"?6:1;if(inBoard(r+d,c)&&!B[r+d][c]){out.push([r+d,c]);if(r===s&&!B[r+2*d][c])out.push([r+2*d,c])}for(const dc of[-1,1])if(inBoard(r+d,c+dc)&&B[r+d][c+dc]&&color(B[r+d][c+dc])!==own)out.push([r+d,c+dc])}else if(t==="n"){[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]].forEach(d=>push(r+d[0],c+d[1]))}else if(t==="k"){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)push(r+dr,c+dc)}else{let ds=[];if(t==="b"||t==="q")ds.push([1,1],[1,-1],[-1,1],[-1,-1]);if(t==="r"||t==="q")ds.push([1,0],[-1,0],[0,1],[0,-1]);for(const d of ds){let rr=r+d[0],cc=c+d[1];while(inBoard(rr,cc)){if(!B[rr][cc])out.push([rr,cc]);else{if(color(B[rr][cc])!==own&&type(B[rr][cc])!=="k")out.push([rr,cc]);break}rr+=d[0];cc+=d[1]}}}return out}function draw(){cb.innerHTML="";for(let r=0;r<8;r++)for(let c=0;c<8;c++){let b=document.createElement("button");b.className="sq "+((r+c)%2?"dark":"light");b.textContent=B[r][c];if(sel&&sel[0]===r&&sel[1]===c)b.classList.add("selected");if(legal.some(x=>x[0]===r&&x[1]===c))b.classList.add("legal");b.onclick=()=>click(r,c);cb.appendChild(b)}}function click(r,c){if(sel&&legal.some(x=>x[0]===r&&x[1]===c)){let p=B[sel[0]][sel[1]],captured=B[r][c];if("♔♚".includes(captured)){cm.textContent="King captured — game over! Press Reset to play again.";return}B[r][c]=p;B[sel[0]][sel[1]]="";if(p==="♙"&&r===0)B[r][c]="♕";if(p==="♟"&&r===7)B[r][c]="♛";turn=turn==="w"?"b":"w";sel=null;legal=[];$("#turn").textContent=turn==="w"?"White to move":"Black to move"}else if(B[r][c]&&color(B[r][c])===turn){sel=[r,c];legal=moves(r,c);cm.textContent=legal.length?"Choose a highlighted square.":"That piece has no available moves."}else{sel=null;legal=[]}draw()}$("#resetC").onclick=()=>openGame("chess");draw()}
Games.puzzle=function puzzle(){let url="",n=3,P=[],moves=0,start=0,timer;root.innerHTML='<div class="config"><div class="box"><label>Upload image</label><input id="file" type="file" accept="image/*"></div><div class="box"><label>Pieces / difficulty</label><select id="size"><option value="3">9 — Easy</option><option value="4">16 — Medium</option><option value="5">25 — Hard</option><option value="6">36 — Expert</option></select></div></div><div class="toolbar"><span class="pill" id="pt">Time: 0s</span><span class="pill" id="pm">Moves: 0</span><button class="ghost" id="newP">New puzzle</button></div><div id="pboard" class="msg">Upload an image to start.</div><div id="pmsg" class="msg"></div>';let file=$("#file"),size=$("#size"),pb=$("#pboard");file.onchange=()=>{if(file.files[0]){url=URL.createObjectURL(file.files[0]);startP()}};size.onchange=()=>{n=+size.value;if(url)startP()};$("#newP").onclick=()=>url&&startP();function solved(){return P.every((v,i)=>v==i)}function startP(){clearInterval(timer);n=+size.value;P=Array.from({length:n*n},(_,i)=>i);do{for(let i=P.length-1;i;i--){let j=Math.random()*(i+1)|0;[P[i],P[j]]=[P[j],P[i]]}}while(solved());moves=0;start=Date.now();timer=setInterval(()=>$("#pt").textContent="Time: "+((Date.now()-start)/1000|0)+"s",500);draw()}function draw(){pb.innerHTML='<div class="pb" style="grid-template-columns:repeat('+n+',1fr)"></div>';let board=pb.firstChild;P.forEach((v,i)=>{let x=document.createElement("button");x.className="piece";let vr=v/n|0,vc=v%n,br=i/n|0,bc=i%n;x.style.backgroundImage='url("'+url+'")';x.style.backgroundSize=n*100+"% "+n*100+"%";x.style.backgroundPosition=(vc*100/(n-1))+"% "+(vr*100/(n-1))+"%";if(v==n*n-1)x.classList.add("empty");x.onclick=()=>swap(i);board.appendChild(x)});$("#pm").textContent="Moves: "+moves}let chosen=null;function swap(i){if(chosen==null)return chosen=i;if(chosen==i)return chosen=null;[P[chosen],P[i]]=[P[i],P[chosen]];chosen=null;moves++;draw();if(solved()){clearInterval(timer);let s=(Date.now()-start)/1000|0;$("#pmsg").textContent="Solved in "+s+"s with "+moves+" moves! 🎉";record("puzzle",s)}}}
Games.typing=function typing(){let texts=["The quick brown fox jumps over the lazy dog while the bright morning sun warms the quiet street.","Small improvements repeated every day can turn into remarkable results. Focus on accuracy first and speed will follow.","A good game gives your mind a challenge and a reason to try again. Stay calm, read carefully, and keep moving forward."],text=texts[Math.random()*texts.length|0],started=false,done=false,start=0,sec=30,timer;root.innerHTML='<div class="tstats"><div class="tstat"><strong id="sec">30</strong>seconds</div><div class="tstat"><strong id="wpm">0</strong>WPM</div><div class="tstat"><strong id="acc">100%</strong>accuracy</div></div><div class="target" id="target"></div><textarea class="typing" id="typing" placeholder="Click Start, then type the passage..." disabled></textarea><div class="toolbar"><button class="primary" id="startT">Start 30s test</button><button class="ghost" id="newT">New passage</button></div><div class="msg" id="tm">Accuracy first. Speed will follow.</div>';let ta=$("#typing");function draw(){target.innerHTML=[...text].map((x,i)=>'<span class="'+(i<ta.value.length?(ta.value[i]==x?"good":"bad"):(i==ta.value.length?"current":""))+'">'+(x==" "?"&nbsp;":x)+"</span>").join("");let good=[...ta.value].filter((x,i)=>x==text[i]).length,a=ta.value.length?Math.round(good/ta.value.length*100):100,e=started?Math.max(.5,(Date.now()-start)/1000):1;wpm.textContent=Math.round(good/5/(e/60));acc.textContent=a+"%"}function finish(){if(done)return;done=true;clearInterval(timer);ta.disabled=true;tm.textContent="Time! Final score: "+wpm.textContent+" WPM at "+acc.textContent+" accuracy.";record("typing",+wpm.textContent)}startT.onclick=()=>{if(started&&!done)return;started=true;done=false;sec=30;start=Date.now();ta.disabled=false;ta.focus();timer=setInterval(()=>{sec--;$("#sec").textContent=sec;if(sec<=0)finish()},1000);draw()};ta.oninput=()=>{draw();if(ta.value.length>=text.length)finish()};newT.onclick=()=>typing();draw()}
